[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "pace"
version = "0.2.0"
dynamic = ["dependencies"]
requires-python = "<3.12"
authors = [{name = "NOAA", email = "oliver.elbert@noaa.gov"}]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE.md"]
classifiers = [
        "Development Status :: 2 - Pre-Alpha",
        "Intended Audience :: Developers",
        "Natural Language :: English",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
]

[project.optional-dependencies]
test = [
    "mpi4py",
    "nbmake",
    "pytest",
]
dev = [
    "pace[test]",
    "pre-commit"
]

[project.urls]
Repository = "https://github.com/NOAA-GFDL/pace"

[tool.setuptools.packages.find]
include = ["pace", "pace.*"]

[tool.setuptools]
include-package-data = true

[tool.black]
line-length = 88
target_version = ['py38']
