stencil_config:
  backend: numpy
  rebuild: false
  validate_args: true
  format_source: false
  device_sync: true
initialization_type: serialbox
initialization_config:
  path: /test_data/c12_6ranks_baroclinic_dycore_microphysics
  serialized_grid: True
nx_tile: 12
nz: 79
dt_atmos: 225
minutes: 4
layout:
  - 1
  - 1
diagnostics_config:
  path: "output.zarr"
  names:
    - u
    - v
    - ua
    - va
    - pt
    - delp
    - qvapor
    - qliquid
    - qice
    - qrain
    - qsnow
    - qgraupel
dycore_config:
  namelist_override: /test_data/c12_6ranks_baroclinic_dycore_microphysics/input.nml
physics_config:
  namelist_override: /test_data/c12_6ranks_baroclinic_dycore_microphysics/input.nml
