stencil_config:
  backend: numpy
  rebuild: false
  validate_args: true
  format_source: false
  device_sync: true
initialization_type: serialbox
initialization_config: {path: /test_data/c12_6ranks_baroclinic_dycore_microphysics, serialized_grid: True}
diagnostics_config:
  path: "output.zarr"
  names:
    - u
    - v
    - ua
    - va
    - pt
    - delp
    - qvapor
    - qliquid
    - qice
    - qrain
    - qsnow
    - qgraupel
