name: "Container Build"

on:
  push:
    branches:
      - 'develop'
  schedule:
    - cron: '0 0 * * 0' # Sundays @ midnight

jobs:
  test-container-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build Dockerfile
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          file: "Dockerfile"
