name: "Lint"

# Run these these whenever ...
on:
  pull_request: # ... a PR is opened / updated
  merge_group: # ... the PR is added to the merge queue
  push:
    branches:
      - main # ... when merging into the main branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Step Python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run lint via pre-commit
        run: |
          pre-commit run --all-files
