name: "Lint"

# Run these these whenever ...
on:
  pull_request: # ... a PR is opened / updated
  merge_group: # ... the PR is added to the merge queue
  push:
    branches:
      - main # ... when merging into the main branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Step Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Only restore (don't save) caches on PRs. New caches created from PRs won't be
      # accessible from other PRs, see workflows/create-cache.yaml.
      - uses: actions/cache/restore@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit_${{ env.pythonLocation }}_${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run lint via pre-commit
        run: pre-commit run --all-files
