name: "Lint"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Pace repository
          uses: actions/checkout@v3.5.2
          with:
            submodules: 'recursive'
        - name: Step Python 3.8.12
          uses: actions/setup-python@v4.6.0
          with:
            python-version: '3.8.12'
        - name: Install OpenMPI for gt4py
          run: |
            sudo apt-get install libopenmpi-dev
        - name: Install Python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements_dev.txt -r requirements_lint.txt
        - name: Run lint via pre-commit
          run: |
            pre-commit run --all-files
