name: "Main unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mlee03/pace:test
    steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: run build_and_test
          run: |
            cp /home/test_scripts/build_and_test.sh .
            chmod + x build_and_test.sh
            ./build_and_test.sh
