name: "Main unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mlee03/test2:test2
    steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: setup environment
          run: |
            source /root/.bashrc
            conda env list
            pip3 install --upgrade pip setuptools wheel
            pip3 install -r requirements_dev.txt -c constraints.txt
            git clone -b store_files https://github.com/mlee03/pace.git tests/main/input
            pytest -x tests/main
