name: "Main unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/pace:3.8
    steps:
        - name: Checkout Pace repository
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: setup env and run tests
          run: |
            cp /home/scripts/setup_env.sh . && chmod +x setup_env.sh
            cp /home/scripts/run_tests.sh . && chmod +x run_tests.sh
            ./setup_env.sh
            ./run_tests.sh
