# TODO: Revert tests back to NOAA-GFDL version (not jjuyeonkim) after
# NDSL/issues#64's PRs close and are all merged. These PRs include:
# https://github.com/NOAA-GFDL/NDSL/pull/218
# https://github.com/NOAA-GFDL/PyFV3/pull/83
# https://github.com/NOAA-GFDL/PySHiELD/pull/58
# https://github.com/NOAA-GFDL/pace/pull/145
#
# For now, I'm manually doing checkouts of NDSL, pyFV3, pySHiELD
# submodules because I don't know of a better way to checkout
# submodules using a specific branch name. 
#
name: "pace main unit tests"

# Run these these whenever ...
on:
  workflow_call: # ... called from a downstream repo
    inputs:
      component_trigger:
        type: boolean
        default: false
        required: false
      component_name:
        type: string
        default: ''
        required: false
  pull_request: # ... a PR is opened / updated
  merge_group:  # ... the PR is added to the merge queue
  push:
    branches:
      - 20250908_namelist_2

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pace_main_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: "Checkout pace@20250908_namelist_2"
        uses: actions/checkout@v5
        with:
          submodules: 'false'
          repository: jjuyeonkim/pace
          path: pace
          ref: 20250908_namelist_4_CI_TEST
          fetch-depth: 0

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11.13
          conda-remove-defaults: true
          auto-activate-base: false
          activate-environment: pace_test_env

      - name: Install mpi (MPICH flavor)
        run: pip install mpich

      - name: "External trigger: Remove existing component in pace/develop"
        if: ${{ inputs.component_trigger }}
        run: rm -rf ${GITHUB_WORKSPACE}/pace/${{inputs.component_name}}

      - name: Install packages
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          pip install .[test]
          pip install numpy==1.26.4

      - name: Print versions
        run: |
          python --version
          pip --version
          pip list

      - name: Prepare input files
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          mkdir tests/main/input
          python examples/generate_eta_files.py tests/main/input

      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          python -m pytest -x tests/main

      - name: Run baroclinic test case
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          mpiexec -np 6 python -m pace.run examples/configs/baroclinic_c48_no_out.yaml
