name: "Main unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mlee03/pace:test
    steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: setup environment 
          run: |
            source /root/.bashrc
            pip3 install --upgrade pip setuptools wheel
            pip3 install -r requirements_dev.txt -c constraints.txt	    
        - name: run tests
          run: |
            source /root/.bashrc
            pytest -x tests/main
