name: "Main unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mlee03/test2:test2
    steps:
        - name: checkout
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: setup environment
          run: |
            conda create -y --name pace python=3.8
            conda activate pace
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements_dev.txt -c constraints.txt
        - name: Clone datafiles
          run: |
            mkdir -p tests/main/input && cd tests/main/input
            git clone -b store_files https://github.com/mlee03/pace.git tmp && mv tmp/*.nc . && rm -rf tmp
        - name: Run all main tests
          run: |
            pytest -x tests/main
