name: "Main unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest    
    container:
      image: mlee03/testing_push:latest
    steps:
        - name: cd to /home
	    cd /home
        - name: Checkout Pace repository
          uses: actions/checkout@v3.5.2
          with:
            submodules: 'recursive'
        - name: setup conda environment
	    python -m pip install --upgrade pip setuptools wheel
	    pip install -r requirements_dev.txt -c constraints.txt
        - name: Clone datafiles
          run: |
            mkdir -p tests/main/input && cd tests/main/input
            git clone -b store_files https://github.com/mlee03/pace.git tmp && mv tmp/*.nc . && rm -rf tmp
        - name: Run all main tests
          run: |
            pytest -x tests/main
