name: "Main unit tests"
on:
  push:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest    
    container:
      image: ghcr.io/mlee03/testing_push:latest
    steps:
        - name: cd home
          run: cd /home
        - name:  oops no git
          run: echo "y" | dnf install git
        - name: Checkout Pace repository
          uses: actions/checkout@v4
        - name: get submodules
          run: |
             git config --global --add safe.directory /home/pace
             git submodule update --recursive
        - name: setup environment
          run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements_dev.txt -c constraints.txt
        - name: Clone datafiles
          run: |
            mkdir -p tests/main/input && cd tests/main/input
            git clone -b store_files https://github.com/mlee03/pace.git tmp && mv tmp/*.nc . && rm -rf tmp
        - name: Run all main tests
          run: |
            pytest -x tests/main
