name: "Main unit tests"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main_unit_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/pace:test
    steps:
        - name: Checkout Pace repository
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        - name: run build_and_test
          run: |
            cp /home/test_scripts/build_and_test.sh .
            chmod +x build_and_test.sh
            ./build_and_test.sh
