name: "Orchestrated model run"

on:
  schedule:
    - cron: '0 0 * * 0' # Sundays @ midnight
  # Temporarily uncomment the next line in case you want to run this workflow on you PR.
  # For example, this can be useful when you are changing the workflow and you don't
  # want to wait until Sunday to see it run.
  # pull_request:

jobs:
  pace_orch_build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    env:
      python_default: '3.12'

    steps:
      - name: Checkout pace
        uses: actions/checkout@v6

      - name: Checkout NDSL
        uses: actions/checkout@v6
        with:
          repository: NOAA-GFDL/NDSL
          path: NDSL
          submodules: recursive

      - name: Checkout pyFV3
        uses: actions/checkout@v6
        with:
          repository: NOAA-GFDL/pyFV3
          path: pyFV3

      - name: Checkout pySHiELD
        uses: actions/checkout@v6
        with:
          repository: NOAA-GFDL/pySHiELD
          path: pySHiELD

      - name: 'Setup Python ${{ env.python_default }}'
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.python_default }}

      - name: Install mpi (MPICH flavor)
        run: pip install mpich

      - name: Install packages
        run: pip install .

      - name: Build and run baroclinic test case
        env:
          FV3_DACEMODE: BuildAndRun
          NDSL_LOGLEVEL: Debug
        run: |
          mpiexec -np 6 python -m pace.run examples/configs/baroclinic_c12_orch_cpu.yaml
